# Escuela Politécnica Nacional
## Facultad de Ingeniería en Sistemas
## Materia: Métodos Numéricos
## Nombre: Daniel Ismael Flores Espín

1. Encuentre las primeras dos iteraciones del método de Jacobi para los siguientes sistemas lineales, por
medio de $𝐱^{(𝟎)} = 0$:

### a)
$3x_1-x_2+x_3=1$,

$3x_1+6x_2+2x_3=0$,

$3x_1+3x_2+7x_3=4$

In [2]:
from src import gauss_jacobi
import numpy as np
import sympy as sp

[02-03 18:32:16][INFO] 2025-02-03 18:32:16.888597
[02-03 18:32:17][INFO] 2025-02-03 18:32:17.197490


In [19]:
import numpy as np

def jacobi_method(A, b, x0, iterations):
    n = len(A)
    x = x0.copy()
    
    for k in range(iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            sum_Ax = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - sum_Ax) / A[i][i]
        
        x = x_new
        print(f"Iteración {k + 1}: {x}")
    
    return x

A = np.array([[3, -1, 1],
              [3, 6, 2],
              [3, 3, 7]], dtype=float)

b = np.array([1, 0, 4], dtype=float)
x0 = np.zeros(len(b)) 
iterations = 15

jacobi_method(A, b, x0, iterations)


Iteración 1: [0.33333333 0.         0.57142857]
Iteración 2: [ 0.14285714 -0.35714286  0.42857143]
Iteración 3: [ 0.07142857 -0.21428571  0.66326531]
Iteración 4: [ 0.04081633 -0.25680272  0.63265306]
Iteración 5: [ 0.03684807 -0.23129252  0.66399417]
Iteración 6: [ 0.03490444 -0.23975543  0.6547619 ]
Iteración 7: [ 0.03516089 -0.23570619  0.65922185]
Iteración 8: [ 0.03502399 -0.23732106  0.65737656]
Iteración 9: [ 0.03510079 -0.23663751  0.65812732]
Iteración 10: [ 0.03507839 -0.23692617  0.65780145]
Iteración 11: [ 0.03509079 -0.23680635  0.65793476]
Iteración 12: [ 0.0350863  -0.23685698  0.65787809]
Iteración 13: [ 0.03508831 -0.23683585  0.65790172]
Iteración 14: [ 0.03508748 -0.23684473  0.6578918 ]
Iteración 15: [ 0.03508782 -0.23684101  0.65789596]


array([ 0.03508782, -0.23684101,  0.65789596])

### b)
$10x_1-x_2=9$,

$-x_1+10x_2-2x_3=7$,

$-2x_2+10x_3=6$

In [20]:
A = np.array([[10, -1, 0],
              [-1, 10, -2],
              [0, -2, 10]], dtype=float)

b = np.array([9, 7, 6], dtype=float)
x0 = np.zeros(len(b)) 
iterations = 15

jacobi_method(A, b, x0, iterations)

Iteración 1: [0.9 0.7 0.6]
Iteración 2: [0.97 0.91 0.74]
Iteración 3: [0.991 0.945 0.782]
Iteración 4: [0.9945 0.9555 0.789 ]
Iteración 5: [0.99555 0.95725 0.7911 ]
Iteración 6: [0.995725 0.957775 0.79145 ]
Iteración 7: [0.9957775 0.9578625 0.791555 ]
Iteración 8: [0.99578625 0.95788875 0.7915725 ]
Iteración 9: [0.99578888 0.95789313 0.79157775]
Iteración 10: [0.99578931 0.95789444 0.79157862]
Iteración 11: [0.99578944 0.95789466 0.79157889]
Iteración 12: [0.99578947 0.95789472 0.79157893]
Iteración 13: [0.99578947 0.95789473 0.79157894]
Iteración 14: [0.99578947 0.95789474 0.79157895]
Iteración 15: [0.99578947 0.95789474 0.79157895]


array([0.99578947, 0.95789474, 0.79157895])

### c)
$10x_1+5x_2=6$,

$5x_1+10x_2-4x_3=25$,

$-4x_2+8x_3-x_4=-11$

$-x_3+5x_4=-11$

In [22]:
A = np.array([[10, 5, 0, 0],
              [5, 10, -4, 0],
              [0, -4, 8, -1],
              [0, 0, -1, 5]], dtype=float)

b = np.array([6, 25, -11, -11], dtype=float)
x0 = np.zeros(len(b)) 
iterations = 15

jacobi_method(A, b, x0, iterations)

Iteración 1: [ 0.6    2.5   -1.375 -2.2  ]
Iteración 2: [-0.65   1.65  -0.4   -2.475]
Iteración 3: [-0.225     2.665    -0.859375 -2.28    ]
Iteración 4: [-0.7325    2.26875  -0.3275   -2.371875]
Iteración 5: [-0.534375    2.73525    -0.53710938 -2.2655    ]
Iteración 6: [-0.767625    2.55234375 -0.2905625  -2.30742188]
Iteración 7: [-0.67617187  2.7675875  -0.38725586 -2.2581125 ]
Iteración 8: [-0.78379375  2.68318359 -0.27347031 -2.27745117]
Iteración 9: [-0.7415918   2.78250875 -0.3180896  -2.25469406]
Iteración 10: [-0.79125437  2.74356006 -0.26558238 -2.26361792]
Iteración 11: [-0.77178003  2.78939423 -0.28617221 -2.25311648]
Iteración 12: [-0.79469712  2.77142113 -0.26194244 -2.25723444]
Iteración 13: [-0.78571057  2.79257158 -0.27144374 -2.25238849]
Iteración 14: [-0.79628579  2.78427779 -0.26026277 -2.25428875]
Iteración 15: [-0.79213889  2.79403779 -0.2646472  -2.25205255]


array([-0.79213889,  2.79403779, -0.2646472 , -2.25205255])

### d)
$4x_1+x_2+x_3+x_5=6$,

$-x_1-3x_2+x_3+x_4=6$,

$2x_1+x_2+5x_3-x_4-x_5=6$

$-x_1-x_2-x_3+4x_4=6$

$2x_2-x_3+x_4+4x_5=6$

In [24]:
A = np.array([[4, 1, 1, 0, 1],
              [-1, -3, 1, 1, 0],
              [2, 1, 5, -1, -1],
              [-1, -1, -1, 4, 0],
              [0, 2, -1, 1, 4]], dtype=float)

b = np.array([6, 6, 6, 6, 6], dtype=float)
x0 = np.zeros(len(b)) 
iterations = 15

jacobi_method(A, b, x0, iterations)

Iteración 1: [ 1.5 -2.   1.2  1.5  1.5]
Iteración 2: [ 1.325 -1.6    1.6    1.675  2.425]
Iteración 3: [ 0.89375 -1.35     1.81     1.83125  2.28125]
Iteración 4: [ 0.8146875  -1.08416667  1.935       1.8384375   2.1696875 ]
Iteración 5: [ 0.74486979 -1.01375     1.89258333  1.91638021  2.06622396]
Iteración 6: [ 0.76373568 -0.97863542  1.90132292  1.90592578  2.00092578]
Iteración 7: [ 0.76909668 -0.98549566  1.87160313  1.92160579  1.98816699]
Iteración 8: [ 0.78143139 -0.99196259  1.87141502  1.91380104  1.98024716]
Iteración 9: [ 0.7850751  -0.99873844  1.8646296   1.91522095  1.98538479]
Iteración 10: [ 0.78718101 -1.00174151  1.8658388   1.91274157  1.98672138]
Iteración 11: [ 0.78729533 -1.00286688  1.86536849  1.91281957  1.98914507]
Iteración 12: [ 0.78708833 -1.00303576  1.86604817  1.91244923  1.98957067]
Iteración 13: [ 0.78685423 -1.00286364  1.8661758   1.91252519  1.98991761]
Iteración 14: [ 0.78669256 -1.00271775  1.8663196   1.9125416   1.98984447]
Iteración 15: [ 0.78

array([ 0.78663842, -1.00261045,  1.86634374,  1.9125736 ,  1.98980337])

2. Repita el ejercicio 1 usando el método de Gauss-Seidel.

In [26]:
import numpy as np

def gauss_seidel_method(A, b, x0, iterations):
    n = len(A)
    x = x0.copy()
    
    for k in range(iterations):
        for i in range(n):
            sum_before = sum(A[i][j] * x[j] for j in range(i))
            sum_after = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x[i] = (b[i] - sum_before - sum_after) / A[i][i]
        
        print(f"Iteración {k + 1}: {x}")
    
    return x
A = np.array([[3, -1, 1],
              [3, 6, 2],
              [3, 3, 7]], dtype=float)

b = np.array([1, 0, 4], dtype=float)
x0 = np.zeros(len(b))
iterations = 15

gauss_seidel_method(A, b, x0, iterations)

Iteración 1: [ 0.33333333 -0.16666667  0.5       ]
Iteración 2: [ 0.11111111 -0.22222222  0.61904762]
Iteración 3: [ 0.05291005 -0.23280423  0.64852608]
Iteración 4: [ 0.03955656 -0.23595364  0.65559875]
Iteración 5: [ 0.0361492  -0.23660752  0.65733928]
Iteración 6: [ 0.03535107 -0.23678863  0.65775895]
Iteración 7: [ 0.03515081 -0.23682839  0.65786182]
Iteración 8: [ 0.03510326 -0.23683891  0.6578867 ]
Iteración 9: [ 0.03509146 -0.2368413   0.65789279]
Iteración 10: [ 0.03508864 -0.23684191  0.65789426]
Iteración 11: [ 0.03508794 -0.23684206  0.65789462]
Iteración 12: [ 0.03508777 -0.23684209  0.65789471]
Iteración 13: [ 0.03508773 -0.2368421   0.65789473]
Iteración 14: [ 0.03508772 -0.2368421   0.65789474]
Iteración 15: [ 0.03508772 -0.23684211  0.65789474]


array([ 0.03508772, -0.23684211,  0.65789474])

### b)

In [27]:
A = np.array([[10, -1, 0],
              [-1, 10, -2],
              [0, -2, 10]], dtype=float)

b = np.array([9, 7, 6], dtype=float)
x0 = np.zeros(len(b)) 
iterations = 15

gauss_seidel_method(A, b, x0, iterations)

Iteración 1: [0.9   0.79  0.758]
Iteración 2: [0.979  0.9495 0.7899]
Iteración 3: [0.99495  0.957475 0.791495]
Iteración 4: [0.9957475  0.95787375 0.79157475]
Iteración 5: [0.99578738 0.95789369 0.79157874]
Iteración 6: [0.99578937 0.95789468 0.79157894]
Iteración 7: [0.99578947 0.95789473 0.79157895]
Iteración 8: [0.99578947 0.95789474 0.79157895]
Iteración 9: [0.99578947 0.95789474 0.79157895]
Iteración 10: [0.99578947 0.95789474 0.79157895]
Iteración 11: [0.99578947 0.95789474 0.79157895]
Iteración 12: [0.99578947 0.95789474 0.79157895]
Iteración 13: [0.99578947 0.95789474 0.79157895]
Iteración 14: [0.99578947 0.95789474 0.79157895]
Iteración 15: [0.99578947 0.95789474 0.79157895]


array([0.99578947, 0.95789474, 0.79157895])

### c)

In [28]:
A = np.array([[10, 5, 0, 0],
              [5, 10, -4, 0],
              [0, -4, 8, -1],
              [0, 0, -1, 5]], dtype=float)

b = np.array([6, 25, -11, -11], dtype=float)
x0 = np.zeros(len(b)) 
iterations = 15

gauss_seidel_method(A, b, x0, iterations)

Iteración 1: [ 0.6    2.2   -0.275 -2.255]
Iteración 2: [-0.5       2.64     -0.336875 -2.267375]
Iteración 3: [-0.72        2.72525    -0.29579688 -2.25915938]
Iteración 4: [-0.762625    2.76299375 -0.27589805 -2.25517961]
Iteración 5: [-0.78149687  2.78038922 -0.26670284 -2.25334057]
Iteración 6: [-0.79019461  2.78841617 -0.26245949 -2.2524919 ]
Iteración 7: [-0.79420808  2.79212025 -0.26050136 -2.25210027]
Iteración 8: [-0.79606012  2.79382952 -0.25959778 -2.25191956]
Iteración 9: [-0.79691476  2.79461827 -0.25918081 -2.25183616]
Iteración 10: [-0.79730913  2.79498224 -0.2589884  -2.25179768]
Iteración 11: [-0.79749112  2.7951502  -0.25889961 -2.25177992]
Iteración 12: [-0.7975751   2.79522771 -0.25885864 -2.25177173]
Iteración 13: [-0.79761385  2.79526347 -0.25883973 -2.25176795]
Iteración 14: [-0.79763174  2.79527998 -0.25883101 -2.2517662 ]
Iteración 15: [-0.79763999  2.79528759 -0.25882698 -2.2517654 ]


array([-0.79763999,  2.79528759, -0.25882698, -2.2517654 ])

### d)

In [29]:
A = np.array([[4, 1, 1, 0, 1],
              [-1, -3, 1, 1, 0],
              [2, 1, 5, -1, -1],
              [-1, -1, -1, 4, 0],
              [0, 2, -1, 1, 4]], dtype=float)

b = np.array([6, 6, 6, 6, 6], dtype=float)
x0 = np.zeros(len(b)) 
iterations = 15

gauss_seidel_method(A, b, x0, iterations)

Iteración 1: [ 1.5     -2.5      1.1      1.525    2.64375]
Iteración 2: [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]
Iteración 3: [ 0.85082845 -1.03530219  1.89436317  1.92747236  2.0093738 ]
Iteración 4: [ 0.7828913  -0.98701859  1.87161643  1.91687229  1.98219533]
Iteración 5: [ 0.78330171 -0.998271    1.86614704  1.91279444  1.98747365]
Iteración 6: [ 0.78616258 -1.00240703  1.86606999  1.91245638  1.98960692]
Iteración 7: [ 0.78668253 -1.00271872  1.86628339  1.9125618   1.98978976]
Iteración 8: [ 0.78666139 -1.0026054   1.86632683  1.91259571  1.98973548]
Iteración 9: [ 0.78663577 -1.00257108  1.86632614  1.91259771  1.98971765]
Iteración 10: [ 0.78663182 -1.00256932  1.86632421  1.91259668  1.98971654]
Iteración 11: [ 0.78663214 -1.00257042  1.86632387  1.9125964   1.98971708]
Iteración 12: [ 0.78663237 -1.0025707   1.86632389  1.91259639  1.98971722]
Iteración 13: [ 0.7866324  -1.00257071  1.86632391  1.9125964   1.98971723]
Iteración 14: [ 0.78663239 -1.002570

array([ 0.78663239, -1.00257069,  1.86632391,  1.9125964 ,  1.98971722])

3. Utilice el método de Jacobi para resolver los sistemas lineales en el ejercicio 1, con TOL = $10^{-3}$.

### a)

In [42]:
import numpy as np

def jacobi_method_with_tolerance(A, b, x0, tol, max_iterations):
    n = len(A)
    x = x0.copy()
    
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            sum_Ax = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - sum_Ax) / A[i][i]

        error = np.linalg.norm(x_new - x, ord=np.inf)
        print(f"Iteración {k + 1}: {x_new}, Error: {error}")
        
        if error < tol:
            print("Convergencia alcanzada.")
            break
        
        x = x_new
    
    return x

A = np.array([[3, -1, 1],
              [3, 6, 2],
              [3, 3, 7]], dtype=float)

b = np.array([1, 0, 4], dtype=float)
x0 = np.zeros(len(b))
tol = 1e-3
max_iterations = 100

jacobi_method_with_tolerance(A, b, x0, tol, max_iterations)

Iteración 1: [0.33333333 0.         0.57142857], Error: 0.5714285714285714
Iteración 2: [ 0.14285714 -0.35714286  0.42857143], Error: 0.35714285714285715
Iteración 3: [ 0.07142857 -0.21428571  0.66326531], Error: 0.2346938775510204
Iteración 4: [ 0.04081633 -0.25680272  0.63265306], Error: 0.04251700680272111
Iteración 5: [ 0.03684807 -0.23129252  0.66399417], Error: 0.031341107871720064
Iteración 6: [ 0.03490444 -0.23975543  0.6547619 ], Error: 0.009232264334305018
Iteración 7: [ 0.03516089 -0.23570619  0.65922185], Error: 0.0044599472442037325
Iteración 8: [ 0.03502399 -0.23732106  0.65737656], Error: 0.0018452959415059533
Iteración 9: [ 0.03510079 -0.23663751  0.65812732], Error: 0.0007507619179839553
Convergencia alcanzada.


array([ 0.03502399, -0.23732106,  0.65737656])

### b)

In [43]:
A = np.array([[10, -1, 0],
              [-1, 10, -2],
              [0, -2, 10]], dtype=float)

b = np.array([9, 7, 6], dtype=float)
x0 = np.zeros(len(b))
tol = 1e-3
max_iterations = 100

jacobi_method_with_tolerance(A, b, x0, tol, max_iterations)

Iteración 1: [0.9 0.7 0.6], Error: 0.9
Iteración 2: [0.97 0.91 0.74], Error: 0.20999999999999996
Iteración 3: [0.991 0.945 0.782], Error: 0.04200000000000004
Iteración 4: [0.9945 0.9555 0.789 ], Error: 0.010500000000000065
Iteración 5: [0.99555 0.95725 0.7911 ], Error: 0.0020999999999999908
Iteración 6: [0.995725 0.957775 0.79145 ], Error: 0.0005250000000001087
Convergencia alcanzada.


array([0.99555, 0.95725, 0.7911 ])

### c)

In [44]:
A = np.array([[10, 5, 0, 0],
              [5, 10, -4, 0],
              [0, -4, 8, -1],
              [0, 0, -1, 5]], dtype=float)

b = np.array([6, 25, -11, -11], dtype=float)
x0 = np.zeros(len(b))
tol = 1e-3
max_iterations = 100

jacobi_method_with_tolerance(A, b, x0, tol, max_iterations)

Iteración 1: [ 0.6    2.5   -1.375 -2.2  ], Error: 2.5
Iteración 2: [-0.65   1.65  -0.4   -2.475], Error: 1.25
Iteración 3: [-0.225     2.665    -0.859375 -2.28    ], Error: 1.0150000000000001
Iteración 4: [-0.7325    2.26875  -0.3275   -2.371875], Error: 0.5318749999999999
Iteración 5: [-0.534375    2.73525    -0.53710938 -2.2655    ], Error: 0.4664999999999999
Iteración 6: [-0.767625    2.55234375 -0.2905625  -2.30742188], Error: 0.24654687500000005
Iteración 7: [-0.67617187  2.7675875  -0.38725586 -2.2581125 ], Error: 0.21524374999999996
Iteración 8: [-0.78379375  2.68318359 -0.27347031 -2.27745117], Error: 0.11378554687499987
Iteración 9: [-0.7415918   2.78250875 -0.3180896  -2.25469406], Error: 0.09932515624999994
Iteración 10: [-0.79125437  2.74356006 -0.26558238 -2.26361792], Error: 0.05250721679687498
Iteración 11: [-0.77178003  2.78939423 -0.28617221 -2.25311648], Error: 0.04583417578125015
Iteración 12: [-0.79469712  2.77142113 -0.26194244 -2.25723444], Error: 0.0242297683105

array([-0.7975133 ,  2.79421162, -0.25896495, -2.25201273])

### d)

In [45]:
A = np.array([[4, 1, 1, 0, 1],
              [-1, -3, 1, 1, 0],
              [2, 1, 5, -1, -1],
              [-1, -1, -1, 4, 0],
              [0, 2, -1, 1, 4]], dtype=float)

b = np.array([6, 6, 6, 6, 6], dtype=float)
x0 = np.zeros(len(b))
tol = 1e-3
max_iterations = 100

jacobi_method_with_tolerance(A, b, x0, tol, max_iterations)

Iteración 1: [ 1.5 -2.   1.2  1.5  1.5], Error: 2.0
Iteración 2: [ 1.325 -1.6    1.6    1.675  2.425], Error: 0.9249999999999998
Iteración 3: [ 0.89375 -1.35     1.81     1.83125  2.28125], Error: 0.4312499999999999
Iteración 4: [ 0.8146875  -1.08416667  1.935       1.8384375   2.1696875 ], Error: 0.26583333333333314
Iteración 5: [ 0.74486979 -1.01375     1.89258333  1.91638021  2.06622396], Error: 0.10346354166666671
Iteración 6: [ 0.76373568 -0.97863542  1.90132292  1.90592578  2.00092578], Error: 0.06529817708333363
Iteración 7: [ 0.76909668 -0.98549566  1.87160313  1.92160579  1.98816699], Error: 0.02971979166666694
Iteración 8: [ 0.78143139 -0.99196259  1.87141502  1.91380104  1.98024716], Error: 0.01233470594618058
Iteración 9: [ 0.7850751  -0.99873844  1.8646296   1.91522095  1.98538479], Error: 0.0067854144965275864
Iteración 10: [ 0.78718101 -1.00174151  1.8658388   1.91274157  1.98672138], Error: 0.0030030709273728418
Iteración 11: [ 0.78729533 -1.00286688  1.86536849  1.9128

array([ 0.78729533, -1.00286688,  1.86536849,  1.91281957,  1.98914507])

4. Utilice el método de Gauss-Siedel para resolver los sistemas lineales en el ejercicio 1, con TOL = $10^{-3}$.

### a)

In [46]:
import numpy as np

def gauss_seidel_method_with_tolerance(A, b, x0, tol, max_iterations):
    n = len(A)
    x = x0.copy()
    
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            sum_before = sum(A[i][j] * x_new[j] for j in range(i))
            sum_after = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - sum_before - sum_after) / A[i][i]
        
        error = np.linalg.norm(x_new - x, ord=np.inf)
        print(f"Iteración {k + 1}: {x_new}, Error: {error}")
        
        if error < tol:
            print("Convergencia alcanzada.")
            break
        
        x = x_new
    
    return x

A = np.array([[3, -1, 1],
              [3, 6, 2],
              [3, 3, 7]], dtype=float)

b = np.array([1, 0, 4], dtype=float)
x0 = np.zeros(len(b)) 
tol = 1e-3
max_iterations = 100

gauss_seidel_method_with_tolerance(A, b, x0, tol, max_iterations)

Iteración 1: [ 0.33333333 -0.16666667  0.5       ], Error: 0.5
Iteración 2: [ 0.11111111 -0.22222222  0.61904762], Error: 0.2222222222222222
Iteración 3: [ 0.05291005 -0.23280423  0.64852608], Error: 0.05820105820105818
Iteración 4: [ 0.03955656 -0.23595364  0.65559875], Error: 0.013353489543965757
Iteración 5: [ 0.0361492  -0.23660752  0.65733928], Error: 0.003407359416429702
Iteración 6: [ 0.03535107 -0.23678863  0.65775895], Error: 0.0007981356647807844
Convergencia alcanzada.


array([ 0.0361492 , -0.23660752,  0.65733928])

### b)

In [47]:
A = np.array([[10, -1, 0],
              [-1, 10, -2],
              [0, -2, 10]], dtype=float)

b = np.array([9, 7, 6], dtype=float)
x0 = np.zeros(len(b)) 
tol = 1e-3
max_iterations = 100

gauss_seidel_method_with_tolerance(A, b, x0, tol, max_iterations)

Iteración 1: [0.9   0.79  0.758], Error: 0.9
Iteración 2: [0.979  0.9495 0.7899], Error: 0.1595000000000001
Iteración 3: [0.99495  0.957475 0.791495], Error: 0.01595000000000013
Iteración 4: [0.9957475  0.95787375 0.79157475], Error: 0.0007975000000000065
Convergencia alcanzada.


array([0.99495 , 0.957475, 0.791495])

### c)

In [48]:
A = np.array([[10, 5, 0, 0],
              [5, 10, -4, 0],
              [0, -4, 8, -1],
              [0, 0, -1, 5]], dtype=float)

b = np.array([6, 25, -11, -11], dtype=float)
x0 = np.zeros(len(b)) 
tol = 1e-3
max_iterations = 100

gauss_seidel_method_with_tolerance(A, b, x0, tol, max_iterations)

Iteración 1: [ 0.6    2.2   -0.275 -2.255], Error: 2.255
Iteración 2: [-0.5       2.64     -0.336875 -2.267375], Error: 1.1
Iteración 3: [-0.72        2.72525    -0.29579688 -2.25915938], Error: 0.21999999999999997
Iteración 4: [-0.762625    2.76299375 -0.27589805 -2.25517961], Error: 0.04262499999999991
Iteración 5: [-0.78149687  2.78038922 -0.26670284 -2.25334057], Error: 0.018871875000000093
Iteración 6: [-0.79019461  2.78841617 -0.26245949 -2.2524919 ], Error: 0.008697734374999877
Iteración 7: [-0.79420808  2.79212025 -0.26050136 -2.25210027], Error: 0.004013474609375067
Iteración 8: [-0.79606012  2.79382952 -0.25959778 -2.25191956], Error: 0.0018520395996093342
Iteración 9: [-0.79691476  2.79461827 -0.25918081 -2.25183616], Error: 0.0008546345935060984
Convergencia alcanzada.


array([-0.79606012,  2.79382952, -0.25959778, -2.25191956])

### d)

In [49]:
A = np.array([[4, 1, 1, 0, 1],
              [-1, -3, 1, 1, 0],
              [2, 1, 5, -1, -1],
              [-1, -1, -1, 4, 0],
              [0, 2, -1, 1, 4]], dtype=float)

b = np.array([6, 6, 6, 6, 6], dtype=float)
x0 = np.zeros(len(b)) 
tol = 1e-3
max_iterations = 100

gauss_seidel_method_with_tolerance(A, b, x0, tol, max_iterations)

Iteración 1: [ 1.5     -2.5      1.1      1.525    2.64375], Error: 2.64375
Iteración 2: [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453], Error: 0.9786458333333332
Iteración 3: [ 0.85082845 -1.03530219  1.89436317  1.92747236  2.0093738 ], Error: 0.4860519748263892
Iteración 4: [ 0.7828913  -0.98701859  1.87161643  1.91687229  1.98219533], Error: 0.0679371456570097
Iteración 5: [ 0.78330171 -0.998271    1.86614704  1.91279444  1.98747365], Error: 0.01125240687911877
Iteración 6: [ 0.78616258 -1.00240703  1.86606999  1.91245638  1.98960692], Error: 0.004136035048103781
Iteración 7: [ 0.78668253 -1.00271872  1.86628339  1.9125618   1.98978976], Error: 0.0005199531084644216
Convergencia alcanzada.


array([ 0.78616258, -1.00240703,  1.86606999,  1.91245638,  1.98960692])

5. El Sistema Lineal

$$2x_1-x_2+x_3=-1$$
$$2x_1+2x_2+2x_3=4$$
$$-x_1-x_2+2x_3=-5$$

tiene la solución $(1, 2, -1)$

a) Muestre que el método de Jacobi con x(0) = 0 falla al proporcionar una buena aproximación
después de 25 iteraciones.

In [15]:
def jacobi_method_with_iterations(A, b, x0, max_iterations):
    n = len(A)
    x = x0.copy()
    
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            sum_Ax = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - sum_Ax) / A[i][i]
        
        print(f"Iteración {k + 1}: {x_new}")
        x = x_new
    
    return x
A = np.array([[2, -1, 1],
              [2,  2, 2],
              [-1, -1, 2]], dtype=float)

b = np.array([-1, 4, -5], dtype=float)
x0 = np.zeros(len(b)) 
max_iterations = 25 

jacobi_method_with_iterations(A, b, x0, max_iterations)

Iteración 1: [-0.5  2.  -2.5]
Iteración 2: [ 1.75  5.   -1.75]
Iteración 3: [2.875 2.    0.875]
Iteración 4: [ 0.0625 -1.75   -0.0625]
Iteración 5: [-1.34375  2.      -3.34375]
Iteración 6: [ 2.171875  6.6875   -2.171875]
Iteración 7: [3.9296875 2.        1.9296875]
Iteración 8: [-0.46484375 -3.859375    0.46484375]
Iteración 9: [-2.66210938  2.         -4.66210938]
Iteración 10: [ 2.83105469  9.32421875 -2.83105469]
Iteración 11: [5.57763672 2.         3.57763672]
Iteración 12: [-1.28881836 -7.15527344  1.28881836]
Iteración 13: [-4.7220459  2.        -6.7220459]
Iteración 14: [ 3.86102295 13.4440918  -3.86102295]
Iteración 15: [8.15255737 2.         6.15255737]
Iteración 16: [ -2.57627869 -12.30511475   2.57627869]
Iteración 17: [-7.94069672  2.         -9.94069672]
Iteración 18: [ 5.47034836 19.88139343 -5.47034836]
Iteración 19: [12.1758709  2.        10.1758709]
Iteración 20: [ -4.58793545 -20.35174179   4.58793545]
Iteración 21: [-12.96983862   2.         -14.96983862]
Iteración 

array([-20.82787284,   2.        , -22.82787284])

b) Utilice el método de Gauss-Siedel con x(0) = 0: para aproximar la solución para el sistema lineal
dentro de 10−5.

In [51]:
def gauss_seidel_method_with_tolerance(A, b, x0, tol, max_iterations):
    n = len(A)
    x = x0.copy()
    
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            sum_before = sum(A[i][j] * x_new[j] for j in range(i))
            sum_after = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - sum_before - sum_after) / A[i][i]
        
        error = np.linalg.norm(x_new - x, ord=np.inf)
        print(f"Iteración {k + 1}: {x_new}, Error: {error}")
        
        if error < tol:
            print("Convergencia alcanzada.")
            break
        
        x = x_new
    
    return x
tol = 1e-5 
max_iterations = 100
gauss_seidel_method_with_tolerance(A, b, x0, tol, max_iterations)

Iteración 1: [-0.5  2.5 -1.5], Error: 2.5
Iteración 2: [ 1.5   2.   -0.75], Error: 2.0
Iteración 3: [ 0.875  1.875 -1.125], Error: 0.625
Iteración 4: [ 1.      2.125  -0.9375], Error: 0.25
Iteración 5: [ 1.03125  1.90625 -1.03125], Error: 0.21875
Iteración 6: [ 0.96875   2.0625   -0.984375], Error: 0.15625
Iteración 7: [ 1.0234375  1.9609375 -1.0078125], Error: 0.1015625
Iteración 8: [ 0.984375    2.0234375  -0.99609375], Error: 0.0625
Iteración 9: [ 1.00976562  1.98632812 -1.00195312], Error: 0.037109375
Iteración 10: [ 0.99414062  2.0078125  -0.99902344], Error: 0.021484375
Iteración 11: [ 1.00341797  1.99560547 -1.00048828], Error: 0.01220703125
Iteración 12: [ 0.99804688  2.00244141 -0.99975586], Error: 0.0068359375
Iteración 13: [ 1.00109863  1.99865723 -1.00012207], Error: 0.0037841796875
Iteración 14: [ 0.99938965  2.00073242 -0.99993896], Error: 0.0020751953125
Iteración 15: [ 1.00033569  1.99960327 -1.00003052], Error: 0.001129150390625
Iteración 16: [ 0.99981689  2.00021362 -

array([ 0.99999571,  2.00000477, -0.99999976])

6. El Sistema Lineal

$$x_1-x_3=0.2$$
$$-\frac{1}{2}x_1+x_2-\frac{1}{4}x_3=-1.425$$
$$x_1-\frac{1}{2}x_2+x_3=2$$

tiene la solución $(0.9, -0.8, 0.7)$.

a) ¿La matriz de coeficientes tiene diagonal estrictamente dominante?

A = $$\begin{bmatrix}
1 & 0 & -1\\
-\frac{1}{2} & 1 &  -\frac{1}{4}\\
1 & -\frac{1}{2} & 1\\
\end{bmatrix}$$

In [18]:
def is_strictly_diagonally_dominant(A):
    n = len(A)
    for i in range(n):
        diagonal = abs(A[i, i])
        off_diagonal_sum = sum(abs(A[i, j]) for j in range(n) if j != i)
        if diagonal <= off_diagonal_sum:
            return False
    return True

A = np.array([[1, 0, -1],
              [-0.5, 1, -0.25],
              [1, -0.5, 1]])

strictly_dominant = is_strictly_diagonally_dominant(A)
print(strictly_dominant)


False


b) Utilice el método iterativo de Gauss-Siedel para aproximar la solución para el sistema lineal con
una tolerancia de 1022 y un máximo de 300 iteraciones.

In [19]:
b = np.array([0.2, -1.425, 2])
x0 = np.zeros(len(b))
tol = 1e-2
max_iterations = 300 

gauss_seidel_method_with_tolerance(A, b, x0, tol, max_iterations)


Iteración 1: [ 0.2    -1.325   1.1375], Error: 1.325
Iteración 2: [ 1.3375    -0.471875   0.4265625], Error: 1.1375
Iteración 3: [ 0.6265625  -1.00507813  0.87089844], Error: 0.7109375
Iteración 4: [ 1.07089844 -0.67182617  0.59318848], Error: 0.4443359375000002
Iteración 5: [ 0.79318848 -0.88010864  0.7667572 ], Error: 0.2777099609375002
Iteración 6: [ 0.9667572  -0.7499321   0.65827675], Error: 0.17356872558593772
Iteración 7: [ 0.85827675 -0.83129244  0.72607703], Error: 0.10848045349121116
Iteración 8: [ 0.92607703 -0.78044223  0.68370185], Error: 0.06780028343200706
Iteración 9: [ 0.88370185 -0.81222361  0.71018634], Error: 0.042375177145004495
Iteración 10: [ 0.91018634 -0.79236024  0.69363354], Error: 0.026484485715627892
Iteración 11: [ 0.89363354 -0.80477485  0.70397904], Error: 0.016552803572267516
Iteración 12: [ 0.90397904 -0.79701572  0.6975131 ], Error: 0.01034550223266728
Iteración 13: [ 0.8975131  -0.80186517  0.70155431], Error: 0.006465938895417134
Convergencia alcanz

array([ 0.90397904, -0.79701572,  0.6975131 ])

c) ¿Qué pasa en la parte b) cuando el sistema cambia por el siguiente?

$$x_1-2x_3=0.2$$
$$-\frac{1}{2}x_1+x_2-\frac{1}{4}x_3=-1.425$$
$$x_1-\frac{1}{2}x_2+x_3=2$$

In [20]:
A = np.array([[1, 0, -2],
              [-0.5, 1, -0.25],
              [1, -0.5, 1]], dtype=float)

b = np.array([0.2, -1.425, 2], dtype=float)
x0 = np.zeros(len(b))
tol = 1e-2 
max_iterations = 300

strictly_dominant = is_strictly_diagonally_dominant(A)
print(f"¿La nueva matriz es diagonal estrictamente dominante? {strictly_dominant}")
gauss_seidel_method_with_tolerance(A, b, x0, tol, max_iterations)

¿La nueva matriz es diagonal estrictamente dominante? False
Iteración 1: [ 0.2    -1.325   1.1375], Error: 1.325
Iteración 2: [ 2.475      0.096875  -0.4265625], Error: 2.275
Iteración 3: [-0.653125   -1.85820313  1.72402344], Error: 3.1281250000000007
Iteración 4: [ 3.64804688  0.8300293  -1.23303223], Error: 4.3011718750000005
Iteración 5: [-2.26606445 -2.86629028  2.83291931], Error: 5.914111328125001
Iteración 6: [ 5.86583862  2.21614914 -2.75776405], Error: 8.131903076171877
Iteración 7: [-5.31552811 -4.77220507  4.92942557], Error: 11.181366729736332
Iteración 8: [10.05885115  4.83678197 -5.64046016], Error: 15.374379253387456
Iteración 9: [-11.08092033  -8.3755752    8.89313272], Error: 21.13977147340775
Iteración 10: [ 17.98626545   9.79141591 -11.0905575 ], Error: 29.06718577593566
Iteración 11: [-21.98111499 -15.18819687  16.38701656], Error: 39.96738044191153
Iteración 12: [ 32.97403311  19.1587707  -21.39464777], Error: 54.95514810762836
Iteración 13: [-42.58929553 -28.0683

array([ 2.15687283e+41,  1.34804552e+41, -1.48285007e+41])

7. Repita el ejercicio 11 usando el método de Jacobi.

b) Utilice el método iterativo de Gauss-Jacobi para aproximar la solución para el sistema lineal con
una tolerancia de 1022 y un máximo de 300 iteraciones.

In [21]:
A = np.array([[1, 0, -2],
              [-0.5, 1, -0.25],
              [1, -0.5, 1]], dtype=float)

b = np.array([0.2, -1.425, 2], dtype=float)
x0 = np.zeros(len(b))  
tol = 1e-2
max_iterations = 300

jacobi_method_with_tolerance(A, b, x0, tol, max_iterations)

Iteración 1: [ 0.2   -1.425  2.   ], Error: 2.0
Iteración 2: [ 4.2    -0.825   1.0875], Error: 4.0
Iteración 3: [ 2.375     0.946875 -2.6125  ], Error: 3.6999999999999997
Iteración 4: [-5.025     -0.890625   0.0984375], Error: 7.3999999999999995
Iteración 5: [ 0.396875   -3.91289062  6.5796875 ], Error: 6.481249999999999
Iteración 6: [13.359375    0.41835938 -0.35332031], Error: 12.962499999999999
Iteración 7: [ -0.50664063   5.16635742 -11.15019531], Error: 13.866015625
Iteración 8: [-22.10039062  -4.46586914   5.08981934], Error: 21.593749999999996
Iteración 9: [ 10.37963867 -11.20274048  21.86745605], Error: 32.480029296874996
Iteración 10: [ 43.93491211   9.23168335 -13.98100891], Error: 35.848464965820305
Iteración 11: [-27.76201782  17.04720383 -37.31907043], Error: 71.69692993164061
Iteración 12: [-74.43814087 -24.63577652  38.28561974], Error: 75.60469017028808
Iteración 13: [ 76.77123947 -29.0726655   64.12025261], Error: 151.20938034057616
Iteración 14: [128.44050522  52.9906

array([ 1.34478913e+43, -7.28028158e+42,  1.56650340e+43])

c) ¿Qué pasa en la parte b) cuando el sistema cambia por el siguiente?

In [7]:
strictly_dominant = is_strictly_diagonally_dominant(A)
print(f"¿La nueva matriz es diagonal estrictamente dominante? {strictly_dominant}")

jacobi_method_with_tolerance(A, b, x0, tol, max_iterations)

¿La nueva matriz es diagonal estrictamente dominante? False
Iteración 1: [ 0.2   -1.425  2.   ], Error: 2.0
Iteración 2: [ 4.2    -0.825   1.0875], Error: 4.0
Iteración 3: [ 2.375     0.946875 -2.6125  ], Error: 3.6999999999999997
Iteración 4: [-5.025     -0.890625   0.0984375], Error: 7.3999999999999995
Iteración 5: [ 0.396875   -3.91289062  6.5796875 ], Error: 6.481249999999999
Iteración 6: [13.359375    0.41835938 -0.35332031], Error: 12.962499999999999
Iteración 7: [ -0.50664063   5.16635742 -11.15019531], Error: 13.866015625
Iteración 8: [-22.10039062  -4.46586914   5.08981934], Error: 21.593749999999996
Iteración 9: [ 10.37963867 -11.20274048  21.86745605], Error: 32.480029296874996
Iteración 10: [ 43.93491211   9.23168335 -13.98100891], Error: 35.848464965820305
Iteración 11: [-27.76201782  17.04720383 -37.31907043], Error: 71.69692993164061
Iteración 12: [-74.43814087 -24.63577652  38.28561974], Error: 75.60469017028808
Iteración 13: [ 76.77123947 -29.0726655   64.12025261], Er

array([ 1.34478913e+43, -7.28028158e+42,  1.56650340e+43])

8. Un cable coaxial está formado por un conductor interno de 0.1 pulgadas cuadradas y un conductor externo de 0.5 pulgadas cuadradas. El potencial en un punto en la sección transversal del cable se describe mediante la ecuación de Laplace. Suponga que el conductor interno se mantiene en 0 volts y el conductor externo se mantiene en 110 volts. Aproximar el potencial entre los dos conductores requiere resolver el siguiente sistema lineal.

El sistema de ecuaciones lineales es:


$$\begin{bmatrix}
4 & -1 & 0 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
-1 & 4 & -1 & 0 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & -1 & 4 & 0 & 0 & -1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & -1 & 4 & -1 & 0 & -1 & 0 & 0 & 0 & 0 & 0 \\
-1 & 0 & 0 & -1 & 4 & -1 & 0 & -1 & 0 & 0 & 0 & 0 \\
0 & 0 & -1 & 0 & -1 & 4 & 0 & 0 & -1 & 0 & 0 & 0 \\
0 & 0 & 0 & -1 & 0 & 0 & 4 & -1 & 0 & -1 & 0 & 0 \\
0 & 0 & 0 & 0 & -1 & 0 & -1 & 4 & -1 & 0 & -1 & 0 \\
0 & 0 & 0 & 0 & 0 & -1 & 0 & -1 & 4 & 0 & 0 & -1 \\
0 & 0 & 0 & 0 & 0 & 0 & -1 & 0 & 0 & 4 & -1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 0 & -1 & 4 & -1 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 0 & -1 & 4 \\
\end{bmatrix}$$
$$\cdot$$
$$\begin{bmatrix}
w_1 \\
w_2 \\
w_3 \\
w_4 \\
w_5 \\
w_6 \\
w_7 \\
w_8 \\
w_9 \\
w_{10} \\
w_{11} \\
w_{12} \\
\end{bmatrix}$$
=
$$\begin{bmatrix}
220 \\
110 \\
110 \\
220 \\
110 \\
110 \\
110 \\
110 \\
110 \\
110 \\
110 \\
220 \\
\end{bmatrix}$$


a. ¿La matriz es estrictamente diagonalmente dominante?

In [8]:
A = np.array([
    [4, -1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [-1, 4, -1, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    [0, -1, 4, 0, 0, -1, 0, 0, 0, 0, 0, 0],
    [-1, 0, 0, 4, -1, 0, -1, 0, 0, 0, 0, 0],
    [0, -1, 0, -1, 4, -1, 0, -1, 0, 0, 0, 0],
    [0, 0, -1, 0, -1, 4, 0, 0, -1, 0, 0, 0],
    [0, 0, 0, -1, 0, 0, 4, -1, 0, -1, 0, 0],
    [0, 0, 0, 0, -1, 0, -1, 4, -1, 0, -1, 0],
    [0, 0, 0, 0, 0, -1, 0, -1, 4, 0, 0, -1],
    [0, 0, 0, 0, 0, 0, -1, 0, 0, 4, -1, 0],
    [0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 4, -1],
    [0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 4],
], dtype=float)

b = np.array([220, 110, 110, 110, 0, 0, 0, 0, 0, 0, 110, 220], dtype=float)

strictly_dominant = is_strictly_diagonally_dominant(A)
print(f"¿La matriz es diagonal estrictamente dominante? {strictly_dominant}")


¿La matriz es diagonal estrictamente dominante? False


b. Resuelva el sistema lineal usando el método de Jacobi con $x_{(0)} = 0$ y TOL = $10^{-2}$.

In [12]:
x0 = np.zeros(len(b))  
tol = 1e-2
max_iterations = 300

solution_gauss_seidel = gauss_seidel_method_with_tolerance(A, b, x0, tol, max_iterations)
print("Solución aproximada con Gauss-Seidel:", solution_gauss_seidel)

Iteración 1: [55.         41.25       37.8125     41.25       20.625      14.609375
 10.3125      7.734375    5.5859375   2.578125   30.078125   63.91601562], Error: 63.916015625
Iteración 2: [75.625      61.015625   46.40625    54.140625   34.375      21.59179688
 16.11328125 21.53808594 26.76147461 11.54785156 51.75048828 74.62799072], Error: 21.67236328125
Iteración 3: [83.7890625  68.64257812 50.05859375 61.06933594 43.21044922 30.00762939
 23.53881836 36.31530762 35.23773193 18.82232666 59.94140625 78.79478455], Error: 14.7772216796875
Iteración 4: [87.42797852 72.67425537 53.17047119 66.04431152 51.26037598 34.91714478
 30.29548645 44.18375015 39.47391987 22.55922318 63.88443947 80.83958983], Error: 8.0499267578125
Iteración 5: [89.67964172 76.02762222 55.23619175 70.30887604 56.3593483  37.76736498
 34.26296234 48.49516749 41.77553058 24.53685045 65.96790195 81.93585813], Error: 5.098972320556641
Iteración 6: [91.58412457 78.29491615 56.51557028 73.0516088  59.40226436 39.423341

c. Repita la parte b) mediante el método de Gauss-Seidel.

In [14]:
solution_gauss_seidel = gauss_seidel_method_with_tolerance(A, b, x0, tol, max_iterations)
print("Solución aproximada con Gauss-Seidel:", solution_gauss_seidel)

Iteración 1: [55.         41.25       37.8125     41.25       20.625      14.609375
 10.3125      7.734375    5.5859375   2.578125   30.078125   63.91601562], Error: 63.916015625
Iteración 2: [75.625      61.015625   46.40625    54.140625   34.375      21.59179688
 16.11328125 21.53808594 26.76147461 11.54785156 51.75048828 74.62799072], Error: 21.67236328125
Iteración 3: [83.7890625  68.64257812 50.05859375 61.06933594 43.21044922 30.00762939
 23.53881836 36.31530762 35.23773193 18.82232666 59.94140625 78.79478455], Error: 14.7772216796875
Iteración 4: [87.42797852 72.67425537 53.17047119 66.04431152 51.26037598 34.91714478
 30.29548645 44.18375015 39.47391987 22.55922318 63.88443947 80.83958983], Error: 8.0499267578125
Iteración 5: [89.67964172 76.02762222 55.23619175 70.30887604 56.3593483  37.76736498
 34.26296234 48.49516749 41.77553058 24.53685045 65.96790195 81.93585813], Error: 5.098972320556641
Iteración 6: [91.58412457 78.29491615 56.51557028 73.0516088  59.40226436 39.423341