# Escuela Politécnica Nacional
## Facultad de Ingeniería en Sistemas
## Materia: Métodos Numéricos
## Nombre: Daniel Ismael Flores Espín

1. Realice las siguientes multiplicaciones matriz-matriz:

a. $$\begin{bmatrix}
2 & -3\\
3 & -1\\
\end{bmatrix}$$
$$\begin{bmatrix}
1 & 5\\
2 & 0\\
\end{bmatrix}$$ 

In [5]:
import numpy as np

def mult_mats(A, B):
    filA, colA = len(A), len(A[0])
    filB, colB = len(B), len(B[0])
    res = [[0]*colB for _ in range(filA)]
    for i in range(filA):
        for j in range(colB):
            for k in range(colA):
                res[i][j] += A[i][k]*B[k][j]
    # Convertir cada elemento a float
    for i in range(filA):
        for j in range(colB):
            res[i][j] = float(res[i][j])
    return res

In [15]:
A = np.array([
    [2, -3],
    [3, -1]
], dtype=float)
B = np.array([
    [1, 5],
    [2, 0]
], dtype=float)
mult_mats(A, B)

[[-4.0, 10.0], [1.0, 15.0]]

b. $$\begin{bmatrix}
2 & -3\\
3 & -1\\
\end{bmatrix}$$
$$\begin{bmatrix}
1 & 5 & -4\\
-3 & 2 & 0\\
\end{bmatrix}$$ 

In [18]:
A = np.array([
    [2, -3],
    [3, -1]
], dtype=float)
B = np.array([
    [1, 5, -4],
    [-3, 2, 0]
], dtype=float)
mult_mats(A, B)

[[11.0, 4.0, -8.0], [6.0, 13.0, -12.0]]

c. $$\begin{bmatrix}
2 & -3 & 1\\
4 & 3 & 0\\
5 & 2 & -4\\
\end{bmatrix}$$
$$\begin{bmatrix}
0 & 1 & -2\\
1 & 0 & -1\\
2 & 3 & -2\\
\end{bmatrix}$$ 

In [20]:
A = np.array([
    [2, -3, 1],
    [4, 3, 0],
    [5, 2, -4]
], dtype=float)
B = np.array([
    [0, 1, -2],
    [1, 0, -1],
    [2, 3, -2]
], dtype=float)
mult_mats(A, B)

[[-1.0, 5.0, -3.0], [3.0, 4.0, -11.0], [-6.0, -7.0, -4.0]]

d. $$\begin{bmatrix}
2 & 1 & 2\\
-2 & 3 & 0\\
2 & -1 & 3\\
\end{bmatrix}$$
$$\begin{bmatrix}
1 & -2\\
-4 & 1\\
0 & 2\\
\end{bmatrix}$$ 

In [23]:
A = np.array([
    [2, 1, 2],
    [-2, 3, 0],
    [2, -1, 3]
], dtype=float)
B = np.array([
    [1, -2],
    [-4, 1],
    [0, 2]
], dtype=float)
mult_mats(A, B)

[[-2.0, 1.0], [-14.0, 7.0], [6.0, 1.0]]

2. Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices:

a. 
$$\begin{bmatrix}
4 & 2 & 6\\
3 & 0 & 7\\
-2 & -1 & -3\\
\end{bmatrix}$$

In [3]:
def verificar_inversa(matriz):
    try:
        det = np.linalg.det(matriz)
        print(f"Determinante: {det}")
        if np.isclose(det, 0):
            print("La matriz no tiene inversa")
        inversa = np.linalg.inv(matriz)
        print("La matriz tiene Inversa:")
        return inversa
    except np.linalg.LinAlgError:
        print("")

In [6]:
A = np.array([
    [4, 2, 6],
    [3, 0, 7],
    [-2, -1, -3]
], dtype=float)
verificar_inversa(A)

Determinante: 0.0
La matriz no tiene inversa



b. 
$$\begin{bmatrix}
1 & 2 & 0\\
2 & 1 & -1\\
3 & 1 & 1\\
\end{bmatrix}$$

In [7]:
A = np.array([
    [1, 2, 0],
    [2, 1, -1],
    [3, 1, 1]
], dtype=float)
verificar_inversa(A)

Determinante: -8.000000000000002
La matriz tiene Inversa:


array([[-0.25 ,  0.25 ,  0.25 ],
       [ 0.625, -0.125, -0.125],
       [ 0.125, -0.625,  0.375]])

c. 
$$\begin{bmatrix}
1 & 1 & -1 & 1\\
1 & 2 & -4 & -2\\
-2 & 1 & 1 & 5\\
-1 & 0 & -2 & 4\\
\end{bmatrix}$$

In [8]:
A = np.array([
    [1, 1, -1, 1],
    [1, 2, -4, -2],
    [-2, 1, 1, 5],
    [-1, 0, -2, 4],
], dtype=float)
verificar_inversa(A)

Determinante: 64.00000000000003
La matriz tiene Inversa:


array([[ 7.50000000e-01, -2.50000000e-01, -2.50000000e-01,
         1.11022302e-16],
       [ 1.25000000e-01,  2.50000000e-01,  3.75000000e-01,
        -3.75000000e-01],
       [ 1.25000000e-01, -1.25000000e-01,  1.25000000e-01,
        -2.50000000e-01],
       [ 2.50000000e-01, -1.25000000e-01, -3.60822483e-17,
         1.25000000e-01]])

d. 
$$\begin{bmatrix}
4 & 0 & 0 & 0\\
6 & 7 & 0 & 0\\
9 & 11 & 1 & 0\\
5 & 4 & 1 & 1\\
\end{bmatrix}$$

In [11]:
A = np.array([
    [4, 0, 0, 0],
    [6, 7, 0, 0],
    [9, 11, 1, 0],
    [5, 4, 1, 1],
], dtype=float)
verificar_inversa(A)

Determinante: 28.00000000000001
La matriz tiene Inversa:


array([[ 2.50000000e-01,  6.16790569e-18,  0.00000000e+00,
         0.00000000e+00],
       [-2.14285714e-01,  1.42857143e-01, -0.00000000e+00,
        -0.00000000e+00],
       [ 1.07142857e-01, -1.57142857e+00,  1.00000000e+00,
        -0.00000000e+00],
       [-5.00000000e-01,  1.00000000e+00, -1.00000000e+00,
         1.00000000e+00]])

3. Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes:

$x_1-x_2+2x_3-x_4=6$

,$x_1-x_3+x_4=4$

,$2x_1+x_2+3x_3-4x_4=-2$

,$-x_2+x_3-x_4=5$

$x_1-x_2+2x_3-x_4=1$

,$x_1-x_3+x_4=1$

,$2x_1+x_2+3x_3-4x_4=2$

,$-x_2+x_3-x_4=-1$

In [14]:
def resolver_sistema(Ab):
    A = Ab[:, :-1] 
    b = Ab[:, -1]
    try:
        solucion = np.linalg.solve(A, b)
        return solucion
    except np.linalg.LinAlgError as e:
        return f"Error: {e}"

Ab_a = np.array([
    [1, -1, 2, -1, 6],
    [1, 0, -1, 1, 4],
    [2, 1, 3, -4, -2],
    [0, -1, 1, -1, 5]
], dtype=np.float32)

solucion_a = resolver_sistema(Ab_a)
print("Solución sistema:", solucion_a)

Solución sistema: [ 3. -6. -2. -1.]


In [15]:
Ab_a = np.array([
    [1, -1, 2, -1, 1],
    [1, 0, -1, 1, 1],
    [2, 1, 3, -4, 2],
    [0, -1, 1, -1, -1]
], dtype=np.float32)

solucion_a = resolver_sistema(Ab_a)
print("Solución sistema:", solucion_a)

Solución sistema: [1. 1. 1. 1.]


4. Encuentre los valores de A que hacen que la siguiente matriz sea singular.

$$\begin{bmatrix}
1 & -1 & \alpha\\
2 & 2 & 1\\
0 & \alpha & -\frac{3}{2}\\
\end{bmatrix}$$

In [5]:
import sympy as sp
alpha = sp.Symbol('alpha')

matriz = sp.Matrix([
    [1, -1, alpha],
    [2,  2,    1],
    [0, alpha, -3/2]
])

determinante = matriz.det()
valores_alpha = sp.solve(determinante, alpha)
print("El determinante de la matriz es:")
print(determinante)
print("\nLos valores de alpha que hacen que la matriz sea singular son:")
print(valores_alpha)


El determinante de la matriz es:
2*alpha**2 - alpha - 6.0

Los valores de alpha que hacen que la matriz sea singular son:
[-1.50000000000000, 2.00000000000000]


5. Resuelva los siguientes sistemas lineales:

a. 
$$\begin{bmatrix}
1 & 0 & 0\\
2 & 1 & 0\\
-1 & 0 & 1\\
\end{bmatrix}$$

$$\begin{bmatrix}
2 & 3 & -1\\
0 & -2 & 1\\
0 & 0 & 3\\
\end{bmatrix}$$

$$\begin{bmatrix}
x_1\\
x_2\\
x_3\\
\end{bmatrix}$$

= $$\begin{bmatrix}
2\\
-1\\
1\\
\end{bmatrix}$$

In [2]:
A_a = np.array([[1, 0, 0], [2, 1, 0], [-1, 0, 1]])
B_a = np.array([[2, 3, -1], [0, -2, 1], [0, 0, 3]])
C_a = np.array([2, -1, 1])

AB_a = np.dot(A_a, B_a)  
X_a = np.linalg.solve(AB_a, C_a)
print("Solución del sistema a:")
print(X_a)

Solución del sistema a:
[-3.  3.  1.]


a. 
$$\begin{bmatrix}
2 & 0 & 0\\
-1 & 1 & 0\\
3 & 2 & -1\\
\end{bmatrix}$$

$$\begin{bmatrix}
1 & 1 & 1\\
0 & 1 & 2\\
0 & 0 & 1\\
\end{bmatrix}$$

$$\begin{bmatrix}
x_1\\
x_2\\
x_3\\
\end{bmatrix}$$

= $$\begin{bmatrix}
-1\\
3\\
0\\
\end{bmatrix}$$

In [3]:
A_b = np.array([[2, 0, 0], [-1, 1, 0], [3, 2, -1]])
B_b = np.array([[1, 1, 1], [0, 1, 2], [0, 0, 1]])
C_b = np.array([-1, 3, 0])

AB_b = np.dot(A_b, B_b)
X_b = np.linalg.solve(AB_b, C_b)
print("Solución del sistema b:")
print(X_b)

Solución del sistema b:
[ 0.5 -4.5  3.5]


6. Factorice las siguientes matrices en la descomposición LU mediante el algoritmo de factorización LU con $l_ii$ = 1 para todas las $i$.

a. 
$$\begin{bmatrix}
1 & 0 & 0\\
2 & 1 & 0\\
-1 & 0 & 1\\
\end{bmatrix}$$

In [13]:
from src import descomposicion_LU

In [14]:
matrices = {
    "a": np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]]),
    "b": np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]]),
    "c": np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]]),
    "d": np.array([
        [2.1756, 4.0231, -2.1732, 5.1967],
        [-4.0231, 6.0000, 0, 1.1973],
        [-1.0000, -5.2107, 1.1111, 0],
        [6.0235, 7.0000, 0, -4.1561]
    ])
}

# Realizar la descomposición LU para cada matriz
for key, matrix in matrices.items():
    resultado = descomposicion_LU(matrix)
    
    # Verifica cuántos valores devuelve la función
    if len(resultado) == 3:
        P, L, U = resultado
        print(f"Matriz {key}:")
        print("P (matriz de permutación):")
        print(P)
        print("L (matriz inferior):")
        print(L)
        print("U (matriz superior):")
        print(U)
    elif len(resultado) == 2:
        L, U = resultado
        print(f"Matriz {key}:")
        print("L (matriz inferior):")
        print(L)
        print("U (matriz superior):")
        print(U)
    else:
        print(f"La función descomposicion_LU devolvió un formato inesperado para la matriz {key}")
    
    print("-" * 50)

[02-03 12:06:57][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   4.5  3.5]]
[02-03 12:06:57][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[02-03 12:06:57][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
Matriz a:
L (matriz inferior):
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]
U (matriz superior):
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
--------------------------------------------------
[02-03 12:06:57][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]
[02-03 12:06:57][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[02-03 12:06:57][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
Matriz b:
L (matriz inferior):
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.1977555

7. Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema
lineal usando la descomposición LU y, a continuación, resuelva los siguientes sistemas lineales.

### a)
$x_1-x_2+2x_3-x_4=6$

,$x_1-x_3+x_4=4$

,$2x_1+x_2+3x_3-4x_4=-2$

,$-x_2+x_3-x_4=5$



In [18]:
import numpy as np
from scipy.linalg import lu

def resolver_sistema_con_LU(A, b):
    """
    Resuelve un sistema de ecuaciones lineales Ax = b utilizando descomposición LU.
    
    Parameters:
        A (np.array): Matriz de coeficientes.
        b (np.array): Vector de términos independientes.
    
    Returns:
        x (np.array): Solución del sistema.
    """
    # Descomposición LU
    P, L, U = lu(A)
    
    # Resolver Ly = Pb
    Pb = np.dot(P, b)
    y = np.linalg.solve(L, Pb)
    
    # Resolver Ux = y
    x = np.linalg.solve(U, y)
    
    return x

sistemas = {
    "a": {
        "A": np.array([[2, -1, 1], [3, 3, 0], [3, 3, 5]]),
        "b": np.array([-1, 0, 4])
    },
    "b": {
        "A": np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]]),
        "b": np.array([1.984, -5.049, -3.895])
    },
    "c": {
        "A": np.array([[2, 0, 0], [1, 1.5, 0], [-3, 0.5, 1]]),
        "b": np.array([3, 4.5, -6.6])
    },
    "d": {
        "A": np.array([
            [2.1756, 4.0231, -2.1732, 5.1967],
            [-4.0231, 6.0000, 0, 1.1973],
            [-1.0000, -5.2107, 1.1111, 0],
            [6.0235, 7.0000, 0, -4.1561]
        ]),
        "b": np.array([17.102, -6.1593, 3.0004, 0.0])
    }
}

for key, sistema in sistemas.items():
    A = sistema["A"]
    b = sistema["b"]
    x = resolver_sistema_con_LU(A, b)
    print(f"Solución del sistema {key}:")
    print(x)
    print("-" * 50)


Solución del sistema a:
[-0.6  0.6  0.8]
--------------------------------------------------
Solución del sistema b:
[1. 1. 1.]
--------------------------------------------------
Solución del sistema c:
[ 1.5  2.  -3.1]
--------------------------------------------------
Solución del sistema d:
[ 4.5834584   0.64756529 22.5539797   7.01162597]
--------------------------------------------------
